---
# =================================================================================
# INSTALL JAVA 1.8
# =================================================================================

- name: Ensure Java 1.7.0 OpenJDK is absent
  yum:
    lock_timeout: 180  # wait up to 3 minutes for a lock ansible/ansible#57189
    name: java-1.7.0-openjdk
    state: absent
  # Java 1.7 was only used when Meza only supported RedHat
  when: ansible_distribution_file_variety == 'RedHat'

- name: Ensure Java 1.8.0 OpenJDK is installed
  yum:
    name: "{{ package_java }}"
    state: present

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644

# ================================================================================
# INSTALL ELASTICSEARCH
# ================================================================================ 

# equivalent to command-line
# rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution_file_variety == 'RedHat'

- name: Add Elasticsearch repository.
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  when: ansible_distribution_file_variety == 'RedHat'

# sudo dnf install --enablerepo=elasticsearch elasticsearch
- name: Ensure elasticsearch installed
  package:
    name: "elasticsearch <= {{ elasticsearch_version }}"
    enablerepo: elasticsearch
    state: present

# Need to perform this check so `lineinfile` doesn't run in Docker. /etc/hosts
# is special in Docker.
# ref: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#updating-the-etchosts-file
# ref: http://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts

- name: Check whether /etc/hosts contains "127.0.0.1"
  command: awk /127.0.0.1/ /etc/hosts
  register: checkhostsfile
  changed_when: false

# Add host name per https://github.com/elastic/elasticsearch/issues/6611
- name: Add localhost to /etc/hosts if needed
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost meza'
    owner: root
    group: root
    mode: 0644
  when: '"127.0.0.1" not in checkhostsfile.stdout'

# ref: http://elasticsearch-users.115913.n3.nabble.com/Elasticsearch-Not-Working-td4059398.html
- name: Ensure dirs from elasticsearch.yml exist and set ownership
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: elasticsearch
    recurse: true
  with_items:
    - "{{ m_meza_data }}/elasticsearch/data"
    - "{{ m_meza_data }}/elasticsearch/scripts"
    - "{{ m_meza_data }}/elasticsearch/log"

# Copy java cacerts to /etc/elasticsearch to resolve issue with openjdk RPM
# update. See: https://discuss.elastic.co/t/elasticsearch-is-incompatible-with-new-versions-of-openjdk-from-redhat/318928/7
- name: Copy extracted java cacerts to /etc/elasticsearch
  copy:
    src: /etc/pki/ca-trust/extracted/java/cacerts
    dest: /etc/elasticsearch/cacerts-java-extracted
    owner: elasticsearch
    group: elasticsearch
    mode: '0444'

# CONFIGURE AND START ELASTICSEARCH
# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html
- name: Configure and Restart Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

# Consider adding this, ref geerlinguy
# - name: Force a restart if configuration has changed.
#   meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: started
    enabled: true
  register: response
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
  when: docker_skip_tasks is not defined or not docker_skip_tasks


# Previously, elasticsearch plugins Head and Kopf (and at one time Bigdesk and
# Inquisitor) were installed here.


#
# Perform checks on Elasticsearch version
#
- name: Check current Elasticsearch version
  uri:
    url: "http://localhost:{{ elasticsearch_http_port }}"
    method: GET
    # user: "{{ elasticsearch_username }}"
    # password: "{{ elasticsearch_password }}"
  register: version_found
  retries: 10
  delay: 10
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: Display current Elasticsearch full version number
  ansible.builtin.debug:
    var: version_found.json.version.number
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: Display desired Elasticsearch version
  ansible.builtin.debug:
    var: elasticsearch_major_version

- name: Set the Elasticsearch major version found
  set_fact:
    es_version_found: "{{ version_found.json.version.number | list | first }}"
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: "Docker image building only: set found version to desired version"
  set_fact:
    es_version_found: "{{ elasticsearch_major_version | list | first }}"
  when: docker_skip_tasks is defined and docker_skip_tasks

- name: Set the Elasticsearch major version desired
  set_fact:
    es_version_desired: "{{ elasticsearch_major_version | list | first }}"

# Do false first. Then force_do_elasticsearch_upgrade can override
- name: Set do_elasticsearch_upgrade to FALSE
  set_fact:
    do_elasticsearch_upgrade: False
  when: es_version_found|int == es_version_desired|int

# Note: force_do_elasticsearch_upgrade not set anywhere. This can be used with:
#       `meza deploy ... --extra-vars "force_do_elasticsearch_upgrade=True"`
- name: Set do_elasticsearch_upgrade to TRUE
  set_fact:
    do_elasticsearch_upgrade: True
  when: (es_version_found|int != es_version_desired|int) or (force_do_elasticsearch_upgrade is defined and force_do_elasticsearch_upgrade)

- name: Include upgrade tasks for ES 5.x --> 6.x
  include_tasks: es_upgrade.yml
  when: do_elasticsearch_upgrade
