---
# =================================================================================
# INSTALL JAVA 1.8
# =================================================================================

- name: Ensure Java 1.7.0 OpenJDK is absent
  ansible.builtin.dnf:
    lock_timeout: 180  # wait up to 3 minutes for a lock ansible/ansible#57189
    name: java-1.7.0-openjdk
    state: absent
  # Java 1.7 was only used when Meza only supported RedHat
  when: ansible_distribution_file_variety == 'RedHat'

- name: Ensure Java 1.8.0 OpenJDK is installed
  ansible.builtin.dnf:
    name: "{{ package_java }}"
    state: present

# Environment setup.
- name: Set JAVA_HOME if configured.
  ansible.builtin.template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644

# ================================================================================
# INSTALL ELASTICSEARCH
# ================================================================================

# equivalent to command-line
# rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elasticsearch GPG key.
  ansible.builtin.rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution_file_variety == 'RedHat'

- name: Add Elasticsearch repository.
  ansible.builtin.template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  when: ansible_distribution_file_variety == 'RedHat'

# sudo dnf install --enablerepo=elasticsearch elasticsearch
- name: Ensure elasticsearch installed
  ansible.builtin.package:
    name: "elasticsearch <= {{ elasticsearch_version }}"
    enablerepo: elasticsearch
    state: present

# Need to perform this check so `lineinfile` doesn't run in Docker. /etc/hosts
# is special in Docker.
# ref: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#updating-the-etchosts-file
# ref: http://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts

- name: Check whether /etc/hosts contains "127.0.0.1"
  ansible.builtin.command: awk /127.0.0.1/ /etc/hosts
  register: elasticsearch_checkhostsfile
  changed_when: false

# Add host name per https://github.com/elastic/elasticsearch/issues/6611
- name: Add localhost to /etc/hosts if needed
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost meza'
    owner: root
    group: root
    mode: 0644
  when: '"127.0.0.1" not in elasticsearch_checkhostsfile.stdout'

# ref: http://elasticsearch-users.115913.n3.nabble.com/Elasticsearch-Not-Working-td4059398.html
- name: Ensure dirs from elasticsearch.yml exist and set ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: elasticsearch
    recurse: true
  with_items:
    - "{{ m_meza_data }}/elasticsearch/data"
    - "{{ m_meza_data }}/elasticsearch/scripts"
    - "{{ m_meza_data }}/elasticsearch/log"

# Copy java cacerts to /etc/elasticsearch to resolve issue with openjdk RPM
# update. See: https://discuss.elastic.co/t/elasticsearch-is-incompatible-with-new-versions-of-openjdk-from-redhat/318928/7
- name: Copy extracted java cacerts to /etc/elasticsearch
  ansible.builtin.copy:
    src: /etc/pki/ca-trust/extracted/java/cacerts
    dest: /etc/elasticsearch/cacerts-java-extracted
    owner: elasticsearch
    group: elasticsearch
    mode: '0444'

# CONFIGURE AND START ELASTICSEARCH
# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html
- name: Configure and Restart Elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: Restart elasticsearch

# Consider adding this, ref geerlinguy
# - name: Force a restart if configuration has changed.
#   meta: flush_handlers

- name: Start Elasticsearch.
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: true
  register: elasticsearch_response
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- name: Make sure Elasticsearch is running before proceeding.
  ansible.builtin.wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
  when: docker_skip_tasks is not defined or not docker_skip_tasks

# If requested, gather ES version info to use when running the reindex task.
- name: Query Elasticsearch root endpoint for version information
  ansible.builtin.uri:
    url: "http://localhost:{{ elasticsearch_http_port }}/"
    method: GET
    return_content: true
    status_code: 200
  register: elasticsearch_version_found
  failed_when: false
  changed_when: false
  when: docker_skip_tasks is not defined or not docker_skip_tasks

# Conditionally include the reindex tasks. This is opt-in to keep playbook idempotent.
# Set `elasticsearch_reindex: true` in inventory/group_vars/host_vars to enable.
- name: Include Elasticsearch reindex tasks when reindexing is requested
  ansible.builtin.include_tasks: es_reindex.yml
  when:
    - (elasticsearch_reindex | default(false)) | bool
    - elasticsearch_version_found.json is defined
    - elasticsearch_version_found.json.version is defined
    - docker_skip_tasks is not defined or not docker_skip_tasks
