---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Allow downgrade because we need to match the version of Elasticsearch exactly
- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"
    allow_downgrade: yes

# We can versionlock in Ansible with the community.general.dnf_versionlock module
- name: Keep kibana package from upgrading with general system updates.
  community.general.dnf_versionlock:
    name: "{{ kibana_downgrade_version }}"
    state: present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
