---
galaxy_info:
  author: Greg Rundlett
  description: Apache HTTP Server installation and configuration for Meza
  company: eQuality Technology
  license: GPL-3.0-or-later
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
    # Debian support is planned for bullseye but not yet implemented
    # - name: Debian
    #   versions:
    #     - bullseye
  galaxy_tags:
    - apache
    - web
    - httpd
    - mediawiki

dependencies:
  - role: set-vars
    tags: always
