#!/bin/bash
# Meza backup cleanup script
# Generated by Ansible - do not modify manually
# Manages compression and cleanup of SQL backup files

set -euo pipefail

# Configuration
BACKUP_DIR="/opt/data-meza/backups"
LOG_FILE="/opt/data-meza/logs/cleanup/backup-cleanup.log"
COMPRESS_AFTER_DAYS="1"
KEEP_DAYS="90"
CLEANUP_OLD_COMPRESSED_DAYS="180"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

# Function to log messages with timestamp
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S'): $1" >> "$LOG_FILE"
}

# Function to compress SQL files older than specified days
compress_old_sql_files() {
    local dir="$1"
    local days="$2"
    
    if [[ -d "$dir" ]]; then
        log_message "Compressing SQL files older than $days days in $dir"
        
        # Find .sql files older than specified days and compress them
        find "$dir" -name "*.sql" -type f -mtime +"$days" -exec gzip {} \; 2>/dev/null || true
        
        # Count compressed files
        local compressed_count
        compressed_count=$(find "$dir" -name "*.sql.gz" -mtime +"$days" -mtime -$(($days + 1)) | wc -l)
        log_message "Compressed $compressed_count SQL files"
    fi
}

# Function to clean up old compressed files
cleanup_old_compressed() {
    local dir="$1"
    local days="$2"
    
    if [[ -d "$dir" ]]; then
        log_message "Removing compressed SQL files older than $days days in $dir"
        
        # Count files to be removed
        local remove_count
        remove_count=$(find "$dir" -name "*.sql.gz" -type f -mtime +"$days" | wc -l)
        
        # Remove old compressed files
        find "$dir" -name "*.sql.gz" -type f -mtime +"$days" -delete 2>/dev/null || true
        
        log_message "Removed $remove_count old compressed SQL files"
    fi
}

# Function to clean up uncompressed SQL files older than keep days
cleanup_old_uncompressed() {
    local dir="$1"
    local days="$2"
    
    if [[ -d "$dir" ]]; then
        log_message "Removing uncompressed SQL files older than $days days in $dir"
        
        # Count files to be removed
        local remove_count
        remove_count=$(find "$dir" -name "*.sql" -type f -mtime +"$days" | wc -l)
        
        # Remove old uncompressed files
        find "$dir" -name "*.sql" -type f -mtime +"$days" -delete 2>/dev/null || true
        
        log_message "Removed $remove_count old uncompressed SQL files"
    fi
}

# Function to display disk usage before and after
check_disk_usage() {
    local dir="$1"
    if [[ -d "$dir" ]]; then
        du -sh "$dir" 2>/dev/null || echo "0B $dir"
    fi
}

# Main cleanup process
main() {
    log_message "Starting Meza backup cleanup process"
    
    # Check initial disk usage
    local initial_usage
    initial_usage=$(check_disk_usage "$BACKUP_DIR")
    log_message "Initial backup directory usage: $initial_usage"
    
    # Step 1: Compress SQL files older than compress_after_days
    compress_old_sql_files "$BACKUP_DIR" "$COMPRESS_AFTER_DAYS"
    
    # Step 2: Remove uncompressed SQL files older than keep_days
    cleanup_old_uncompressed "$BACKUP_DIR" "$KEEP_DAYS"
    
    # Step 3: Remove compressed files older than cleanup_old_compressed_days
    cleanup_old_compressed "$BACKUP_DIR" "$CLEANUP_OLD_COMPRESSED_DAYS"
    
    # Check final disk usage
    local final_usage
    final_usage=$(check_disk_usage "$BACKUP_DIR")
    log_message "Final backup directory usage: $final_usage"
    
    # Clean up old log files (keep last 30 days of cleanup logs)
    find "$(dirname "$LOG_FILE")" -name "backup-cleanup.log*" -type f -mtime +30 -delete 2>/dev/null || true
    
    log_message "Meza backup cleanup process completed"
}

# Check if backup directory exists
if [[ ! -d "$BACKUP_DIR" ]]; then
    log_message "Backup directory $BACKUP_DIR does not exist, creating it"
    mkdir -p "$BACKUP_DIR"
    chown meza-ansible:apache "$BACKUP_DIR" 2>/dev/null || true
    chmod 755 "$BACKUP_DIR"
fi

# Run main cleanup
main

# Exit successfully
exit 0