---

- name: "Check if server log database exists"
  shell: 'mysqlshow "{{ meza_server_log_db }}" | grep -v Wildcard | grep -o {{ meza_server_log_db }}'
  register: register_server_log
  failed_when: false
  run_once: true

- name: "Set fact if server log database DOES exist"
  set_fact:
    server_log_exists: true
  when: register_server_log.rc == 0

- name: "Set fact if server log database DOES NOT exist"
  set_fact:
    server_log_exists: false
  when: register_server_log.rc != 0

- name: "Copy meza_server_log.sql to remote database hosts"
  copy:
    src: "{{ m_meza }}/src/roles/meza-log/files/meza_server_log.sql"
    dest: "/tmp/meza_server_log.sql"
    owner: "{{ ansible_user | default(ansible_env.USER) }}"
    group: meza-ansible
    mode: u+r,g+r,o+r
  run_once: true
  when: not server_log_exists

- name: "Import server log database structure"
  community.mysql.mysql_db:
    name: "{{ meza_server_log_db }}"
    state: import
    target: "/tmp/meza_server_log.sql"
  run_once: true
  when: not server_log_exists


#
# Disk space usage
#
- name: "Check if disk_space table exists"
  shell: "sudo mysql -e\"USE {{ meza_server_log_db }}; SHOW TABLES LIKE 'disk_space'\" | grep disk_space"
  register: register_disk_space
  failed_when: false
  run_once: true

- name: "Set fact if disk_space table DOES exist"
  set_fact:
    disk_space_exists: true
  when: register_disk_space.rc == 0

- name: "Set fact if disk_space table DOES NOT exist"
  set_fact:
    disk_space_exists: false
  when: register_disk_space.rc != 0

- name: "Copy table_disk_space.sql to remote database hosts"
  copy:
    src: "{{ m_meza }}/src/roles/meza-log/files/table_disk_space.sql"
    dest: "/tmp/table_disk_space.sql"
    owner: "{{ ansible_user | default(ansible_env.USER) }}"
    group: meza-ansible
    mode: u+r,g+r,o+r
  run_once: true
  when: not disk_space_exists


- name: "Create table disk_space if not exists"
  community.mysql.mysql_db:
    name: "{{ meza_server_log_db }}"
    state: import
    target: "/tmp/table_disk_space.sql"
  run_once: true
  when: not disk_space_exists


#
# Put performance scripts in place
#
- name: Ensure logging scripts in place
  template:
    src: "{{ item }}.j2"
    dest: "{{ m_deploy }}/{{ item }}"
    mode: '0755'
  with_items:
    - server-performance.sh
    - disk-space-usage.sh
