---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed) or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed) }}"

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- include_tasks: databases.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

- include_tasks: users.yml
  when: docker_skip_tasks is not defined or not docker_skip_tasks

# don't run replication in check mode
- include_tasks: replication.yml
  when: >
    (docker_skip_tasks is not defined)
    or
    (not docker_skip_tasks)
    or
    not ansible_check_mode
