---

- name: Ensure app servers have local config directory
  file:
    path: "{{ m_config_deploy_dir }}/public"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true

# At this point the controller must have a local config. Now force it upon the
# app servers.
# This is run on all app servers (assuming conditions apply)
- name: Ensure app servers have config from controller
  synchronize:
    src: "{{ m_local_public }}/"
    dest: "{{ m_config_deploy_dir }}/public"
    recursive: true
    delete: true
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"

# The commands above seemed to be putting the files in m_config_deploy_dir without
# properly setting` file modes. This does a recursive setting of those modes.
- name: Ensure app servers local config directory and contents configured
  file:
    path: "{{ m_config_deploy_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true
