---
# We're called from the site.yml playbook
# The haproxy role takes care of front-end and back-end port handling

# Netdata used to install in /opt but now uses packages across the system.
# "/usr/sbin/netdata" is the main binary.
- name: Check if Netdata is present
  ansible.builtin.stat:
    path: "/usr/sbin/netdata"
  register: netdata_present

- name: Debug - Netdata not installed
  ansible.builtin.debug:
    msg: "netdata not installed"
  when: not netdata_present.stat.exists

- name: Debug - Netdata installed
  ansible.builtin.debug:
    msg: "netdata installed"
  when: netdata_present.stat.exists

# yamllint disable rule:line-length
- name: Verify Netdata installer script integrity
  ansible.builtin.shell: |
    set -o pipefail
    if [ "39321e7a8e05f0054f93df1824189abd" = "$(curl -Ss https://get.netdata.cloud/kickstart.sh | tee /tmp/netdata-kickstart.sh | md5sum | cut -d ' ' -f 1)" ]; then
      echo "OK, VALID: Netdata installer script integrity verified"
      exit 0
    else
      echo "FAILED, INVALID: Netdata installer script integrity check failed"
      exit 1
    fi
  args:
    executable: /bin/bash
  register: netdata_integrity_check
  become: false
  changed_when: false
  when: not netdata_present.stat.exists
# yamllint enable rule:line-length

## It will be running once installed
# The default port is 19999, but we do not open any port in HAProxy so it's not
# accessible externally unless the admin wants to do so manually.
# It is recommended to just use port forwarding over SSH to access the Netdata dashboard securely.
# You can do this in your ssh config, or with VSCode port forwarding.
- name: Install Intel/AMD 64bit static build of Netdata
  ansible.builtin.command: >
    sh /tmp/netdata-kickstart.sh
    --stable-channel
    --install-prefix {{ m_install_dir }}
    --build-only
    --non-interactive
    --disable-telemetry
  become: false
  changed_when: true
  when: not netdata_present.stat.exists and netdata_integrity_check.rc == 0
