---

# Perform checks on user input
# FIXME #179: This isn't working: spaces and dashes getting through
# FIXME #298: Dashes break MariaDB. Figure out how to allow them.
- assert:
    that: 'wiki_id is search("[a-zA-Z0-9_]")'
    msg: "Your wiki ID may only include letters, numbers and underscores"

# Required to fix scope of wiki_id variable when set via prompt. Ref #954.
- name: Set fact - wiki_id
  set_fact:
    wiki_id: "{{ wiki_id }}"

- name: Sync configurations (FIXME do we need this)
  include_role:
    name: sync-configs

- name: Add wiki to configuration
  include_role:
    name: configure-wiki

- name: Re-sync config to app servers
  include_role:
    name: sync-configs

# This whole role needs inspection. It does way too much.
# Was breaking 'create wiki' because the mediawiki-tables.SQL was stale
- name: Use verify-wiki to make sure new wiki is setup
  include_role:
    name: verify-wiki

# Wikis are totally built at this point, but search needs rebuilding?
# Pretty sure this is taken care of in the MedidaWiki role.
- name: (Re-)build search index for each wiki
  shell: "bash {{ m_deploy }}/elastic-rebuild-all.sh {{ wiki_id }}"
  run_once: true
  tags:
    - search-index
