---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution_file_variety }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- name: Ensure GlusterFS is started and enabled at boot.
  service:
    name: "{{ glusterfs_daemon }}"
    state: started
    enabled: true

- name: Ensure Gluster brick and mount directories exist.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ gluster_brick_dir }}"
    - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: "{{ gluster_replicas }}"
    cluster: "{{ groups['app_servers'] | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: true
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
