---

- name: Ensure proper Meza version
  become: true
  become_user: "meza-ansible"
  # Ref #1149 for TMPDIR environment var
  environment:
    TMPDIR: "{{ m_tmp }}"
  git:
    repo: "{{ meza_repository_url }}"
    dest: "{{ m_meza }}"
    version: "{{ enforce_meza_version }}"
    track_submodules: false
    recursive: false
    umask: "0002"
  when: enforce_meza_version is defined
