---

- hosts: app_servers
  become: true

  # prompt for wiki_id and wiki_name
  vars_prompt:
    - name: "wiki_id"
      prompt: |
        Enter the desired wiki identifier to delete.

        Type the wiki ID and press [ENTER]:
      private: false

  roles:
    - set-vars
    - delete-wiki-wrapper
