---

- hosts: app_servers
  become: true
  tasks:

    - name: Set vars
      ansible.builtin.include_role:
        name: set-vars
      tags:
        - always

    - name: (Re-)build search index for each wiki
      ansible.builtin.command: "bash {{ m_config_deploy_dir }}/elastic-rebuild-all.sh"
      run_once: true
      changed_when: true
      tags:
        - search-index

    - name: Rebuild SemanticMediaWiki data for each wiki  # noqa: command-instead-of-shell
      # Using shell for output redirection - more efficient than register+copy for large output
      # The script already redirects STDERR so here we can just redirect STDOUT to a log file.
      ansible.builtin.shell: "bash {{ m_config_deploy_dir }}/smw-rebuild-all.sh > {{ m_data_logs_dir }}/smw-rebuilddata/smw-rebuild-all.log"
      run_once: true
      changed_when: true
      tags:
        - smw-data
