---

- hosts: app_servers
  become: true
  tasks:

    - name: Set vars
      include_role:
        name: set-vars
      tags:
        - always

    - name: (Re-)build search index for each wiki
      shell: "bash {{ m_config_deploy_dir }}/elastic-rebuild-all.sh"
      run_once: true
      tags:
        - search-index

    - name: Rebuild SemanticMediaWiki data for each wiki
      shell: "bash {{ m_config_deploy_dir }}/smw-rebuild-all.sh > {{ m_data_logs_dir }}/smw-rebuilddata/smw-rebuild-all.log"
      run_once: true
      tags:
        - smw-data
