---
# Playbook to verify file permissions and group membership are correct
# What it does:
# Verify meza-ansible group memberships and critical directory permissions
# Also verify and correct MediaWiki directory ownership and permissions
# The verify-permissions playbook can be run independently to check and fix permissions
#
# USAGE:
#
# If you are in the config directory, it will be picked up automatically
# cd /opt/meza/config
# Run ansible-playbook specifying the config as well as the inventory
# using 'localhost, --connection=local' for local runs
# and finally specifying the 'env' extra var to satisfy the 'set-vars' role
# ANSIBLE_CONFIG=/opt/meza/config/ansible.cfg ansible-playbook -i localhost, --connection=local  /opt/meza/src/playbooks/verify-permissions.yml -e env=monolith

- name: Verify Meza permissions and group membership
  hosts: all
  gather_facts: true
  become: true

# All playbooks should load critical Meza variables first
  pre_tasks:
    - name: Load critical Meza variables
      ansible.builtin.include_role:
        name: set-vars

  tasks:
    - name: Include permission verification role
      ansible.builtin.include_role:
        name: verify-permissions
      tags:
        - verify
        - permissions
        - groups
