---
- name: Ensure old ImageMagick installed from Meza RPM is removed (RedHat/CentOS only)
  yum:
    lock_timeout: 180  # wait up to 3 minutes for a lock ansible/ansible#57189
    name: imagemagick-7.0.3-1.x86_64
    state: absent
  when: ansible_distribution_file_variety == 'RedHat'

- name: Ensure Imagemagick and ghostscript installed
  package:
    name: "{{ package_imagemagick }}"
    state: present
  tags:
    - latest

- name: Copy xpdf bin64 files to /usr/local/bin
  copy:
    src: xpdf-3.04-bin64/
    dest: /usr/local/bin/
