---

# Define all the Ansible community modules that we need for Meza to work
#
# Note that thanks to support from RedHat
# we only need to 'dnf install ansible' on Rocky Linux 8 and RHEL 8
# https://github.com/freephile/meza/issues/51#issuecomment-2452963358
# 
# Install from the 'config' directory with
# ansible-galaxy collection install -r requirements.yml
# or the full invocation would be
# ansible-galaxy collection install -vvv -r ../requirements.yml -p ../collections/
# You can leave off the 'collections path' argument since that is stipulated in config/ansible.cfg
#
# Newer versions of ansible-galaxy do not require the 'collection' keyword
# collections:
#     - 'community.general'
#     - 'ansible.posix'
#     - 'gluster.gluster'
#     - 'community.mysql'

roles:
  #  https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/kibana/documentation/
  # had to manually install with 
  # sudo ansible-galaxy role install --force https://github.com/geerlingguy/ansible-role-kibana/archive/refs/tags/4.0.2.tar.gz
  - name: geerlingguy.kibana
    version: 4.0.2
