---

# this task is duplicated from check-for-changes.yml
- name: Set autodeployer slack icon URL
  ansible.builtin.set_fact:
    # yamllint disable-line rule:line-length
    autodeployer_slack_icon_url: "{{ autodeployer.slack_icon_url | default('https://github.com/freephile/meza/raw/dev/src/roles/configure-wiki/files/logo.png') }}"
  when: autodeployer is defined

- name: Notify deploy is starting
  community.general.slack:
    token: "{{ autodeployer.slack_token }}"
    msg: "{{ deploy_type | default('Deploy') }} starting"
    channel: "{{ autodeployer.slack_channel }}"
    username: "{{ autodeployer.slack_username }}"
    icon_url: "{{ autodeployer_slack_icon_url }}"
    color: "good"
    link_names: 1
  when:
    - autodeployer is defined
    - autodeployer.slack_token is defined
    - autodeployer.slack_channel is defined
    - autodeployer.slack_username is defined
    - autodeployer_slack_icon_url is defined

- name: Deploy
  ansible.builtin.shell: >
    meza deploy-unlock {{ env }}
    && meza deploy {{ env }} {{ deploy_args }}
  failed_when: false
  register: autodeployer_result
  changed_when: autodeployer_result.rc == 0

- name: Declare success
  ansible.builtin.set_fact:
    autodeployer_status: "complete"
    autodeployer_notification_color: "good"
  when: autodeployer_result.rc == 0

- name: Declare failure
  ansible.builtin.set_fact:
    autodeployer_status: "failed"
    autodeployer_notification_color: "danger"
  when: autodeployer_result.rc != 0

- name: "Notify deploy {{ autodeployer_status }}"
  community.general.slack:
    token: "{{ autodeployer.slack_token }}"
    msg: "{{ deploy_type | default('Deploy') }} {{ autodeployer_status }}"
    channel: "{{ autodeployer.slack_channel }}"
    username: "{{ autodeployer.slack_username }}"
    icon_url: "{{ autodeployer_slack_icon_url }}"
    color: "{{ autodeployer_notification_color }}"
    link_names: 1
  when:
    - autodeployer is defined
    - autodeployer.slack_token is defined
    - autodeployer.slack_channel is defined
    - autodeployer.slack_username is defined
    - autodeployer_slack_icon_url is defined
