name: Lint YAML Files

on:
  push:
    branches:
      - main

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint ./**/*.yml ./**/*.yaml